[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data-worldgen"
version = "0.1.0"
description = "A world generation toolkit"

readme = "README.md"

dependencies = [

]

[tool.setuptools.packages.find]
where = ["src"]