"Extracted from full list of planets on Wookieepedia."

PLANETS_LIST = [
    "Aaloth",
    "Aargonar",
    "Ab Dalis",
    "Abafar",
    "Abednedo",
    "Abelor",
    "Abregado-rae",
    "Abrion Major",
    "Absanz",
    "Abtin",
    "Actlyon",
    "Adelphi",
    "Aeos Prime",
    "Aeten II",
    "Affa",
    "Affadar",
    "Agamar",
    "Agaris",
    "Agoliba-Ado",
    "Agoliba-Ena",
    "Ah Re Won",
    "Ahch-To",
    "Ajara",
    "Akiva",
    "Alamass",
    "Alaris",
    "Albrae-Don",
    "Alderaan",
    "Aldhani",
    "Aleen",
    "Aleen Minor",
    "Allst Prime",
    "Allyuen",
    "Aloxl",
    "Aloxor",
    "Alpinn",
    "Alsakan",
    "Aludia",
    "Alun",
    "Alzoc III",
    "Ambria",
    "Amethia Prime",
    "Ammon IV",
    "Ammuud",
    "Anantapar",
    "Anaxes",
    "Andelm IV",
    "Ando",
    "Ando Prime",
    "Andraven",
    "Anelsana",
    "Angcord",
    "Angoth",
    "Ankhural",
    "Anoat",
    "Ansion",
    "Antar",
    "Anthan Prime",
    "Antillion",
    "Anzat",
    "Aq Vetina",
    "Aquaris",
    "Arbiflux",
    "Arbooine",
    "Arbra",
    "Arcana",
    "Ardennia",
    "Argai Minor",
    "Arges",
    "Aria Prime",
    "Aricho",
    "Aridus",
    "Arieli",
    "Aris",
    "Arkania",
    "Arkanis",
    "Arli",
    "Arreyel",
    "Artemesium",
    "Artiod Minor",
    "Arvala-7",
    "Ashas Ree",
    "Askaji",
    "Asmeru",
    "Asternin",
    "Asusto",
    "Achrann",
    "Acoda",
    "Aravin",
    "Arissia",
    "Attin",
    "Aytuu",
    "Atalia",
    "Athulla",
    "Atoa",
    "Atollon",
    "Atraken",
    "Atterra Alpha",
    "Atterra Bravo",
    "Atterra Primo",
    "Aubadas",
    "Auratera",
    "Avedot",
    "Avidich",
    "Axxila",
    "Aynaboni",
    "B'ankora homeworld",
    "Bakura",
    "Balagash",
    "Ballum",
    "Balmorra",
    "Balnab",
    "Balosar",
    "Bamayar",
    "Bamayar IX",
    "Banas",
    "Banchii",
    "Bandomeer",
    "Bantoo",
    "Baori Minor",
    "Bar'leth",
    "Baraan-Fa",
    "Barab I",
    "Bardelberan 7",
    "Bardotta",
    "Barkhesh",
    "Bartokan V",
    "Barton IV",
    "Bartool",
    "Bastatha",
    "Basteel",
    "Bastion",
    "Batonn",
    "Batuu",
    "Batuv",
    "Bavana",
    "Bavva",
    "Bedlam",
    "Begamor",
    "Behpour",
    "Belderone",
    "Belladoon",
    "Bellassa",
    "Benath",
    "Bendeluum",
    "Benetage",
    "Benglor",
    "Bernilla",
    "Berzite",
    "Bespin",
    "Bestine IV",
    "Bestoon",
    "Bilbringi",
    "Bilzen",
    "Birren",
    "Birukay",
    "Bith",
    "Bleuf",
    "Blutopia",
    "Bogano",
    "Bonadan",
    "Boneworld",
    "Boothi XII",
    "Bora Vio",
    "Bormus",
    "Botajef",
    "Bothawui",
    "Botor",
    "Boz Pity",
    "Bracca",
    "Bray",
    "Brendok",
    "Brentaal IV",
    "Bri'n",
    "Bromlarch",
    "Burnin Konn",
    "Bursant",
    "Byss",
    "Cabarria",
    "Cadomai Prime",
    "Calcoraan",
    "Calior",
    "Caloria",
    "Camson",
    "Candovant",
    "Cantonica",
    "Caraad",
    "Caragon-Viner",
    "Carajam",
    "Cardota",
    "Carida",
    "Carlac",
    "Carnelion IV",
    "Castell",
    "Castilon",
    "Catadra",
    "Cato Neimoidia",
    "Cavas",
    "CeSai",
    "Celwis",
    "Cerea",
    "Cermau",
    "Cerosha",
    "Chaaktil",
    "Chad",
    "Chadawa",
    "Chagar IX",
    "Chal Hudda",
    "Chalacta",
    "Champala",
    "Chandar's Folly",
    "Chandel",
    "Chandrila",
    "Chardis",
    "Charros IV",
    "Chasmeene",
    "Chenley Prime",
    "Chespea",
    "Chibbier",
    "Cholganna",
    "Chommell Minor",
    "Chorin",
    "Choss",
    "Christophsis",
    "Chrona",
    "Cianap",
    "Clerion",
    "Codia I",
    "Colla IV",
    "Colonial Station Camco",
    "Commenor",
    "Cona",
    "Concord Dawn",
    "Corellia",
    "Corulag",
    "Coruscant",
    "Corvus",
    "Cos Secundu",
    "Cosia",
    "Cosmatanic Steppes gas giant",
    "Council",
    "Courtsilius",
    "Coyerti",
    "Crait",
    "Crucival",
    "Crul",
    "Csilla",
    "Cuyacan",
    "Cyclor",
    "Cyphar",
    "Cyrillia",
    "Cyrkon",
    "Czerialus",
    "D'Assem",
    "D'Qar",
    "Daedus",
    "Daghee",
    "Dagobah",
    "Daivak",
    "Daiyu",
    "Dallenor",
    "Dalna",
    "Damanos",
    "Dandoran",
    "Dantooine",
    "Darlyn Boda",
    "Daro",
    "Dasoor",
    "Dathomir",
    "Davnar II",
    "Dawk",
    "Daxam IV",
    "Daxan Beta",
    "Deko Neimoidia",
    "Delphon",
    "Delrian Prison Planet",
    "Demesel",
    "Demir",
    "Denash",
    "Denon",
    "Deppani",
    "Derenzil",
    "Deris-plata",
    "Dermos",
    "Desinta",
    "Desix",
    "Devalok",
    "Devaron",
    "Dhandu",
    "Dianth",
    "Dinutu",
    "Dinwa Prime",
    "Dinzo",
    "Distilon",
    "Dol'har Hyde",
    "Donovia",
    "Dorin",
    "Dotharian",
    "Dowut",
    "Drahgor III",
    "Dromund Kaas",
    "Dubraib",
    "Durkteel",
    "Duro",
    "Dwartii",
    "Dybbron III",
    "Dybrin",
    "E'ronoh",
    "Eadu",
    "Edis VII",
    "Egips",
    "Eiram",
    "Elkeenar",
    "Elom",
    "Elphrona",
    "Elrood",
    "Empress Teta",
    "Ena",
    "Endor",
    "Enthenium",
    "Enujut",
    "Ephemera",
    "Epikonia",
    "Epiphany",
    "Er'Kit",
    "Erebus",
    "Eriadu",
    "Eroudac",
    "Ertegas",
    "Escalan",
    "Escander",
    "Escarte",
    "Eshan",
    "Espinar",
    "Espirion",
    "Esseles",
    "Etai",
    "Etti IV",
    "Eufornis Major",
    "Eufornis Minor",
    "Everon",
    "Exegol",
    "Exodeen",
    "Eyo-Dajuritz",
    "Ezaraa",
    "Falleen",
    "Farana",
    "Farhava Beta",
    "Fedalle",
    "Federian",
    "Fedovoi End",
    "Feenix",
    "Felucia",
    "Fermic",
    "Ferrix",
    "Fest",
    "Fillithar",
    "Firrhana",
    "Florrum",
    "Fobaris",
    "Fondor",
    "Foran Tutha",
    "Forrn",
    "Freerock",
    "Fresia",
    "Frong",
    "GH-531",
    "GUHL-JO387O",
    "Gaaten",
    "Gabdor",
    "Gabredor III",
    "Galaan",
    "Galagolos V",
    "Galara",
    "Galator III",
    "Galdi",
    "Galidraan",
    "Galidraan III",
    "Galidraan IV",
    "Galjaero",
    "Gallios",
    "Gallowyss",
    "Galmerah",
    "Galpos II",
    "Galzez",
    "Gamerong",
    "Gamorr",
    "Gan Moradir",
    "Gand",
    "Gannaria",
    "Gansevor",
    "Ganthel",
    "Garel",
    "Gargon",
    "Gatalenta",
    "Gazian",
    "Genetia",
    "Gentes",
    "Geonosis",
    "Geptish",
    "Gerrenthum",
    "Gesaral Beta",
    "Ghorman",
    "Gibad",
    "Giermos",
    "Gigor",
    "Giju",
    "Gilvaanen",
    "Glee Anselm",
    "Gloam",
    "Golatha",
    "Golus",
    "Gonda",
    "Gorse",
    "Gossam",
    "Graf-World",
    "Grange",
    "Gravlex Med",
    "Grizmallt",
    "Guagenia",
    "Guat'a",
    "Guiteica",
    "Gulhadar",
    "Gutretee",
    "Gwongdeen",
    "Gyndine",
    "Hadros",
    "Hafernia",
    "Haidoral Prime",
    "Haiklet",
    "Haileap",
    "Halcyon",
    "Haneli",
    "Harkrova I",
    "Harloff Minor",
    "Haruun Kal",
    "Hays Major",
    "Hays Minor",
    "Hazun",
    "Hebekrr Major",
    "Hebekrr Minor",
    "Helikoprion",
    "Hetzal Prime",
    "Hevurion",
    "Hinari",
    "Hindle",
    "Hintis IV",
    "Hirara",
    "Hisseen",
    "Hissrich",
    "Hofsgut",
    "Hon-Tallos",
    "Horuz",
    "Hosnian",
    "Hosnian Prime",
    "Hosra",
    "Hoth",
    "Hovun IV",
    "Hoxim",
    "Hudalla",
    "Huk",
    "Humbarine",
    "Huulia",
    "Hynestia Prime",
    "Hyperkarn",
    "Hypori",
    "I'vorcia Prime",
    "Iakar",
    "Ibaar",
    "Ibbe",
    "Iego",
    "Ikkrukk",
    "Iktotchon",
    "Iloh",
    "Ilum",
    "Imena",
    "Imroosia",
    "Imvur",
    "Inad",
    "Indoumodo",
    "Insk",
    "Inusagi",
    "Ione",
    "Ipsidon",
    "Irff",
    "Iridonia",
    "Irudiru",
    "Isde Naha",
    "Iskalon",
    "Isobe",
    "Isolt",
    "Ison",
    "Itapi Prime",
    "Ithor",
    "Itzeho",
    "Ivarujar",
    "Ivera X",
    "Ixilix",
    "Jabiim",
    "Jaelen",
    "Jafan",
    "Jaguada",
    "Jakku",
    "Jalindi",
    "Jamiron",
    "Janx II",
    "Japeal",
    "Jarbanov",
    "Jaresh",
    "Jaymir",
    "Jekara",
    "Jelucan",
    "Jeosyn",
    "Jereth VI",
    "Jestefad",
    "Jeyell",
    "Jhas",
    "Jiruus",
    "Jondora",
    "Judakann",
    "Kadavo",
    "Kaddak",
    "Kakra",
    "Kal'Shebbol",
    "Kalarba",
    "Kalee",
    "Kalevala",
    "Kalist VI",
    "Kaller",
    "Kamil",
    "Kamino",
    "Kanzi",
    "Karalle",
    "Karaxis",
    "Kardoa",
    "Karfeddion",
    "Karkaris",
    "Karlinus",
    "Karolia",
    "Kashyyyk",
    "Kaspas",
    "Kavith III",
    "Keitum",
    "Keldooine",
    "Kellux",
    "Kenari",
    "Kennerla",
    "Kerev Doi",
    "Kergans",
    "Kerkoidia",
    "Kesh",
    "Kessar",
    "Kessel",
    "Kethmandi",
    "Ketzali",
    "Khofar",
    "Khomm",
    "Kidron",
    "Kiffex",
    "Kiffu",
    "Kijimi",
    "Kilia IV",
    "Kilotowa",
    "Kindosorn",
    "Kinoss",
    "Kinrah",
    "Kintan",
    "Kintoni",
    "Kinyen",
    "Kirdo III",
    "Kirima",
    "Kiros",
    "Kirtarkin",
    "Kizan",
    "Klatooine",
    "Klonoid",
    "Klytus V",
    "Koboh",
    "Kol Iben",
    "Kondoraan",
    "Konkiv",
    "Kooriva",
    "Koorivar homeworld",
    "Korrilan IV",
    "Korrus",
    "Kortatka",
    "Koru Neimoidia",
    "Koshaga",
    "Kotab",
    "Kowak",
    "Krassis",
    "Kreeling",
    "Kril'Dor",
    "Krownest",
    "Krystar",
    "Ktath'atn",
    "Kuat",
    "Kubindi",
    "Kudo",
    "Kullgroon",
    "Kundu Minor",
    "Kupoh",
    "Kwenn",
    "Lafete",
    "Lah'mu",
    "Lahn",
    "Land",
    "Langsha-Raang",
    "Langston",
    "Lannik",
    "Lanteeb",
    "Lanupa",
    "Lanz Carpo",
    "Lasan",
    "Lateron",
    "Lau",
    "Lechra",
    "Ledalau",
    "Lefrani",
    "Lehanis",
    "Lenahra",
    "Leoxo",
    "Lespectus",
    "Lew'el",
    "Lexrul",
    "Li'eta",
    "Li-Toran",
    "Lioaoin heartworld",
    "Lira San",
    "Livno III",
    "Llanic",
    "Lokori",
    "Lola Sayu",
    "Lolet",
    "Lonera",
    "Loreth",
    "Lothal",
    "Lotho Minor",
    "Lowick",
    "Luprora",
    "Lutrillia",
    "Luzalite",
    "Lysatra",
    "Mahranee",
    "Malachor",
    "Malador",
    "Malastare",
    "Malathon IX",
    "Maldo Kreis",
    "Maldroth",
    "Malenko",
    "Malian",
    "Malorin",
    "Malpaz",
    "Manaan",
    "Mandalore",
    "Mannius Eight",
    "Manpha",
    "Manress",
    "Mapuzo",
    "Marca",
    "Mardona III",
    "Mareg IX",
    "Maridun",
    "Marleyvane",
    "Maryx Minor",
    "Massoss",
    "Mataou",
    "Mathas",
    "Mearalis II",
    "Megalox Beta",
    "Mek'tradi",
    "Melacon",
    "Merj",
    "Merokia",
    "Metagos",
    "Metalorn",
    "Metellos",
    "Mexeluine",
    "Midarr",
    "Miekos",
    "Mijos",
    "Mikkia",
    "Milvayne",
    "Mimban",
    "Mina-Rau",
    "Minfar",
    "Minntooine",
    "Mirial",
    "Mirrin Prime",
    "Miser",
    "Miv'rah",
    "Mokivj",
    "Molos",
    "Mon Cala",
    "Mon Gazza",
    "Monta",
    "Montross",
    "Mooga",
    "Moorja",
    "Moraband",
    "Moraga",
    "Morak",
    "Morellia",
    "Morlana One",
    "Mountain",
    "Mulita",
    "Murkhana",
    "Mustafar",
    "Muunilinst",
    "Mydasos",
    "Mygeeto",
    "Mykapo",
    "Mynos III",
    "Myomar",
    "N'Zoth",
    "NaJedha",
    "Naalol",
    "Naator",
    "Naboo",
    "Nacronis",
    "Nag Ubdur",
    "Najan-Rovi",
    "Najiba",
    "Najra-Va",
    "Nakadia",
    "Nal Hutta",
    "Nam Chorios",
    "Nanth'ri",
    "Naporar",
    "Nar Kanji",
    "Naraka",
    "Narkina",
    "Narq",
    "Navlaas",
    "Necropolis",
    "Neelanon",
    "Neftali",
    "Neimoidia",
    "Nelgenam",
    "Nelvaan",
    "Nephryn",
    "Nepotis",
    "Neral",
    "Neralus",
    "Neskar",
    "Netalych",
    "Nettehi",
    "Nevarro",
    "Niamos",
    "Nightsend",
    "Nimban",
    "Ningoth",
    "Niraya",
    "Nixus",
    "Noctu",
    "Noe'ha'on",
    "Nooroyo",
    "Nordis Prime",
    "Norisyn",
    "Norsid",
    "Norulac",
    "Nothoiin",
    "Noult",
    "Numidian Prime",
    "Nyriaan",
    "Oanne",
    "Oba Diah",
    "Obroa-skai",
    "Ocahont",
    "Odona",
    "Ogem",
    "Oisin",
    "Ojom",
    "Oktaro",
    "Olega",
    "Olgothon",
    "Oliu",
    "Omaka",
    "Omereth",
    "Onderon",
    "Onod I",
    "Ontotho",
    "Ool",
    "Oon",
    "Oosalon",
    "Ootoo Prime",
    "Orchis",
    "Ord Cestus",
    "Ord Jannak",
    "Ord Mantell",
    "Ord Mynock",
    "Ord Pardron",
    "Ord Tiddell",
    "Ordo",
    "Orin",
    "Orish",
    "Orn Kios",
    "Ornfra",
    "Orondia",
    "Orra",
    "Orto",
    "Orto Plutonia",
    "Oru",
    "Oshira",
    "Osseriton",
    "Ossus",
    "Oulanne",
    "Ovanis",
    "Pabu",
    "Pacara",
    "Pagodon",
    "Palagosal",
    "Pam'ba",
    "Pamarthe",
    "Pammant",
    "Pandem Nai",
    "Panisia",
    "Panna",
    "Parau VI",
    "Parein II",
    "Parnassos",
    "Parwa",
    "Pasaana",
    "Pasher",
    "Pastoria",
    "Patitite Pattuna",
    "Patriim",
    "Patrolia",
    "Paucris Major",
    "Peg Shar I",
    "Pendarr III",
    "Pergoomi",
    "Peridea",
    "Perimako Major",
    "Persis IX",
    "Petris Major",
    "Petrusia",
    "Phateem",
    "Phatrong",
    "Pheryon",
    "Philaxia",
    "Phindar",
    "Phorsa Gedd",
    "Phothrell",
    "Phrill",
    "Picadir",
    "Pii",
    "Pijal",
    "Pillio",
    "Pion",
    "Pipada",
    "Pippip 3",
    "Pipyyr",
    "Piroket",
    "Pkori",
    "Planet X",
    "Plazir-15",
    "Pleknok",
    "Plexis",
    "Plin Minor",
    "Polaar",
    "Polis Massa",
    "Pollillus",
    "Polmanar",
    "Polyneus",
    "Ponemah Terminal",
    "Pothor",
    "Prakith",
    "Prefsbelt IV",
    "Pria",
    "Primea",
    "Protobranch",
    "Pujool",
    "Pyra",
    "Pzandias",
    "Qhulosk",
    "Qualai",
    "Quarmendy",
    "Quarzite",
    "Quell",
    "Quermia",
    "Ques",
    "Quila",
    "Quintil",
    "Raddan",
    "Radhii",
    "Raithal",
    "Rajtiri",
    "Rakata Prime",
    "Ralltiir",
    "Randon",
    "Rango Tan",
    "Rapacc",
    "Rattatak",
    "Raxus Prime",
    "Raxus Secundus",
    "Raydonia",
    "Raysho",
    "Reamma",
    "Reena",
    "Reerez",
    "Refnu",
    "Rekkana",
    "Rendel",
    "Rendili",
    "Rentor",
    "Retta",
    "Reventine",
    "Rex Strata",
    "Rhen Var",
    "Rhigar",
    "Rhinnal",
    "Ribento",
    "Ridlay",
    "Ridley",
    "Riflor",
    "Rilias II",
    "Rina Major",
    "Ringo Vinda",
    "Rinn",
    "Rion",
    "Rior",
    "Riosa",
    "Ripurni",
    "Rishi",
    "Risso",
    "Rocedila",
    "Rodia",
    "Rohm",
    "Ronaphaven",
    "Ronika",
    "Ronyards",
    "Rothana",
    "Routh",
    "Roxuli",
    "Rumitaka",
    "Ruoss Minor",
    "Rushan IX",
    "Ruusan",
    "Rylorii Minor",
    "Ryloth",
    "Rystan",
    "Safrifa",
    "Sagamore",
    "Sakavi Tar",
    "Saki",
    "Sakreen",
    "Saleucami",
    "Salient I",
    "Salient II",
    "Salliche",
    "Salstan",
    "Sammun",
    "Samovar",
    "Sanjin",
    "Saracor",
    "Sarapin",
    "Sarka",
    "Sarrish",
    "Sarumo",
    "Sarvchi",
    "Sason",
    "Satotai",
    "Savareen",
    "Scarif",
    "Schesa",
    "Scipio",
    "Seatos",
    "Secundus Ando",
    "Sedri",
    "Sedri Minor",
    "Seelos",
    "Segra Milo",
    "Selenus",
    "Selonia",
    "Selvernis",
    "Sembla",
    "Senna",
    "Serelia",
    "Serenno",
    "Sergia",
    "Serolonis",
    "Sesid",
    "Seswenna",
    "Setor",
    "Setron",
    "Sevarcos",
    "Seylott",
    "Sha Qarot",
    "Shadda-Bi-Boran",
    "Shantipole",
    "Shihon",
    "Shili",
    "Shownar",
    "Shu-Torun",
    "Shuraden",
    "Sibensko",
    "Silla",
    "Simoth",
    "Siquay",
    "Sirpar",
    "Sissubo",
    "Skako",
    "Skako Minor",
    "Skara Nal",
    "Skaradosh",
    "Skorii-Lei",
    "Skuhl",
    "Skye",
    "Sljee",
    "Soika",
    "Solitair",
    "Son-tuul",
    "Sorgal 12",
    "Sorgan",
    "Souwecer",
    "Spalex",
    "Spintir",
    "Spira",
    "Sposia",
    "Sran",
    "Sri Karna",
    "Sriluur",
    "Sterdic IV",
    "Stewjon",
    "Stic",
    "Stivic",
    "Stobar",
    "Strokill Prime",
    "Sturg Ganna's homeworld",
    "Stygeon Prime",
    "Suba",
    "Subterrel",
    "Sullust",
    "Sump",
    "Sunrise",
    "Suria",
    "Sy Myrth",
    "Synjax",
    "Syrinx Prime",
    "Taanab",
    "Tah'Nuhna",
    "Tais Brabbo",
    "Takobo",
    "Takodana",
    "Taloraan",
    "Talus",
    "Tammuz-an",
    "Tamsye Prime",
    "Tanalorr",
    "Tangenine",
    "Tansyl 5",
    "Taris",
    "Tarsunt",
    "Tatooine",
    "Taul",
    "Taw Provode",
    "Tehar",
    "Tei-Untis",
    "Telerath",
    "Temako",
    "Temerancé",
    "Tenoo",
    "Tepasi",
    "Teralov",
    "Teriona",
    "Teth",
    "Tevel",
    "Thabeska",
    "Thall",
    "Tharben",
    "Tharnaka",
    "The Contessa's homeworld",
    "The Deep",
    "Thelj",
    "Therezar",
    "Theron",
    "Thisspias",
    "Tholoth",
    "Thorat IX",
    "Thorum",
    "Thrad",
    "Throffdon",
    "Thule",
    "Thunder",
    "Thune",
    "Thustra",
    "Thyferra",
    "Tibrin",
    "Tieos",
    "Tierfon",
    "Tiferep Major",
    "Tiikae",
    "Tinnel IV",
    "Tinoon",
    "Tish",
    "Tiss'ell",
    "Todouhar",
    "Tokmia",
    "Toledian",
    "Tolis",
    "Toola",
    "Toprawa",
    "Torrenoteer Minor",
    "Toshaal",
    "Touksingal",
    "Toydaria",
    "Tozil",
    "Tralgaria",
    "Tralus",
    "Trandosha",
    "Trasse",
    "Travyx Prime",
    "Trenwyth",
    "Triffis",
    "Trionak",
    "Trivar II",
    "Troiken",
    "Troithe",
    "Trymant IV",
    "Tsaokallus",
    "Tsevuka",
    "Tund",
    "Tunguray",
    "Tureen VII",
    "Turkana",
    "Turrak",
    "Twon Ketee",
    "Tyegin",
    "Tynna",
    "Tython",
    "Uba IV",
    "Ubardia",
    "Uchinao",
    "Ueda",
    "Ukio",
    "Umbara",
    "Umme",
    "Uquine",
    "Urajab",
    "Urch",
    "Uro",
    "Ushruu",
    "Utapau",
    "Uvena Prime",
    "Uveron",
    "Uyter",
    "Vaal",
    "Vadran",
    "Vagadarr Prime",
    "Valahari",
    "Valboraan",
    "Vallt",
    "Valo",
    "Valron",
    "Valtos",
    "Vandor",
    "Vanqor",
    "Var-Shaa",
    "Vardos",
    "Variax",
    "Varkana",
    "Varl",
    "Varnak",
    "Varovia",
    "Vashka",
    "Vassek",
    "Vavarna",
    "Veelo",
    "Velusia",
    "Vendaxa",
    "Vernid",
    "Veros",
    "Vertseth",
    "Verzan",
    "Vespaara",
    "Vetine",
    "Vexos",
    "Viamarr",
    "Vikir",
    "Vincorba",
    "Vir Aphshire",
    "Virujansi",
    "Vixnix",
    "Vixoseph I",
    "Vjun",
    "Vlemoth Port",
    "Vodran",
    "Vorlag",
    "Vorzyd V",
    "Vrogas Vas",
    "Vulpter",
    "Vurdon Ka",
    "Vuundalla",
    "Vyndal",
    "Wadi Raffa",
    "Warlentta",
    "Waskiro",
    "Watassay",
    "Water",
    "Wayland",
    "Wecacoe",
    "Weik",
    "Wellspring of Life",
    "Whiforla II",
    "Wick 111",
    "Wind",
    "Wobani",
    "Wrea",
    "Wynkahthu",
    "Xais",
    "Xala",
    "Xendek",
    "Xibariz",
    "Xirl",
    "Xorrn",
    "Yabol Opa",
    "Yag'Dhul",
    "Yaga Minor",
    "Yakorki",
    "Yamradi",
    "Yar Togna",
    "Yarma",
    "Yarrum",
    "Yavin Prime",
    "Yeksom",
    "Yerbana",
    "Yir Tangee",
    "Ylagia",
    "Ylesia",
    "Yotch",
    "Yoturba",
    "Yout",
    "Yungbrii",
    "Zaadja",
    "Zastiga",
    "Zav Alox",
    "Zayron",
    "ZeHeth",
    "Zeffo",
    "Zeitooine",
    "Zhadalene",
    "Zhanox",
    "Ziost",
    "Zoh",
    "Zolan",
    "Zoph",
    "Zygerria",
    "Zyzar",
    "Zyzek",
]
